# Generated by Django 5.0.2 on 2024-05-17 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrationapp.order')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrationapp.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Order_vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fuel_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrationapp.order')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrationapp.warehouse')),
            ],
        ),
    ]
