# Generated by Django 5.0.2 on 2024-05-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0003_order_warehouse_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='warehouse_name',
        ),
    ]
