# Generated by Django 5.0.2 on 2024-05-22 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0004_remove_order_warehouse_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
