# Generated by Django 5.2 on 2025-05-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0005_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='planned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
