# Generated by Django 5.2 on 2025-05-22 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0006_order_estimated_end_order_planned_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='order',
            name='starting_point',
        ),
        migrations.CreateModel(
            name='Order_destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrationapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Order_warehouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_location', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrationapp.order')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrationapp.warehouse')),
            ],
        ),
    ]
