# Generated by Django 5.2 on 2025-05-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0008_remove_order_product_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Бензин А-95 преміум', 'Бензин А-95 преміум'), ('Бензин А-95', 'Бензин А-95'), ('Бензин А-92', 'Бензин А-92'), ('Дизельне паливо', 'Дизельне паливо'), ('Газ автомобільний', 'Газ автомобільний')], default='Бензин А-95', max_length=50),
        ),
    ]
