# Generated by Django 5.2 on 2025-05-26 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0009_vehicle_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='order_destinations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrationapp.order_destinations'),
        ),
    ]
