# Generated by Django 5.2 on 2025-05-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0010_alter_order_product_order_destinations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_destinations',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='order_destinations',
            name='position',
            field=models.PositiveIntegerField(default=99999),
        ),
    ]
