# Generated by Django 5.2 on 2025-05-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0011_alter_order_destinations_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_destinations',
            options={},
        ),
        migrations.RemoveField(
            model_name='order_destinations',
            name='position',
        ),
    ]
