# Generated by Django 5.2 on 2025-05-26 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0012_alter_order_destinations_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_destinations',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_destinations', to='registrationapp.order'),
        ),
        migrations.AlterField(
            model_name='order_warehouses',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_warehouses', to='registrationapp.order'),
        ),
    ]
