# Generated by Django 5.2 on 2025-06-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0013_alter_order_destinations_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
