# Generated by Django 5.2 on 2025-06-05 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0017_driver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='order_vehicle',
            field=models.ForeignKey(default=999999, on_delete=django.db.models.deletion.CASCADE, to='registrationapp.order_vehicle'),
            preserve_default=False,
        ),
    ]
