# Generated by Django 5.2 on 2025-06-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0019_remove_driver_order_vehicle_order_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_driver',
            name='user',
        ),
    ]
