# Generated by Django 5.2 on 2025-06-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0020_remove_order_driver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
